baseURL = "https://nayeem0072.github.io/"
languageCode = "en-us"
title = "Nayeem Islam"
theme = "archie"
copyright = " © Nayeem"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4


[params]
favicon = "https://img.icons8.com/color/code"
og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "*Coding with Perspectives*"
description = "Blog and Personal Portfolio of Nayeem Islam"
disableComments = false
menuicons = true
googleAnalytics = "G-MB506MVBGL"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nayeem0072"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nayeem-islam-b4b71612b/"

[[params.social]]
name = "Leetcode"
icon = "code"
url = "https://leetcode.com/inayeem/"

[[params.social]]
name = "Steam"
icon = "tv"
url = "https://steamcommunity.com/id/fenrir19/"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://github.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
pre  = "home"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
pre  = "file-text"
weight = 2

[[menu.main]]
name = "Search"
url = "/search"
pre  = "search"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
pre  = "tag"
weight = 4

[[menu.main]]
name = "Projects"
url = "/projects"
pre  = "layers"
weight = 5

[[menu.main]]
name = "CV"
url = "/resume"
pre  = "layout"
weight = 6

[[menu.main]]
name = "About"
url = "/about"
pre  = "coffee"
weight = 7

